### PR TITLE
feat: add remaining hotkeys

### LINKED ISSUE #103: Hotkeys
Implement the following hotkeys:

  - [x] `Up/Down`: Moves selection up and down in search, banis, navigator, settings, etc.
  - [x] `Left`: Up
  - [x] `j`: Up
  - [x] `Right`: Down
  - [x] `l` (lowercase L): Down
  - [x] `Page Up`: Up (Used by presenter remotes)
  - [x] `Page Down`: Down
  - [x] `Home`: First line (search result not search bar and nav/bookmarks/etc as expected)
  - [x] `End`: Same logic but with last line.
  - [x] `C-Up`: First line in navigator. Using it on first line will move to last line of previous shabad order ID. Search/Bani/Settings move to first result.
  - [x] `C-Down`: Last line in navigator. Using it on last line will move to first line of next shabad order ID. Search/Bani/Settings move to last result.
  - [x] `Esc`: Clear screen
  - [x] `C-S-b`: Clear screen (used by presenter remotes)
  - [x] `Enter`: activate current line (search, nav, bani, etc). Should work from cleared screen so you can show the same line you were displaying prior to escaping.
  - [x] `Enter`: when used inside the search input box, activate top/first search result.
  - [x] `Spacebar`: autotoggle lines in nav. First use sets "main line", second use from any other line adds new var called "next line" which was the jump line + 1 and goes back to main line. Next line cannot be main line. if shabad has any "rahao" line set as main, none of them can be set as Next line.
  - [x] `b`: autotoggle (used by presenter remotes)
  - [x] `C-Spacebar`: changes the main line to the highlighted line.
  - [x] `S-.`: Always move autotoggle to next line. If already on next line, do nothing. Should not change next line var.
  - [x] `S-,`: Always move autotoggle to main line. If already on main line, do nothing. Should not change any var.
  - [x] `1-G`: Numerical hotkey for 1 - 25 lines. Not to be used on search screen.
  - [x] `C-h`: Toggle built-in controller visibility (hide/show)
  - [x] `C-/`: search page
  - [x] `C-b`: bookmarks page
  - [x] `C-y`: history page
  - [x] `C-Enter`: nav page
  - [x] `C-f`: toggle presenter fullscreen
  - [x] `C-r`: reload/refresh
  - [x] `S-f`: Toggle Controller fullscreen
  - [x] `C-q`: quit all windows of application and possibly preserve state for next startup

Future reservations:

  -  `C-s` or `C-p`: save/print menu for lines/shabad with customizations
  -  `C-c`: copy menu should show additional copy fields in pop-up with different (labelled) hotkeys for fields
  - `C-t`: open new tab
  - `C-w`: close tab
  - `C-n`: open new window
  -  `k`: play/pause (this key is between j and l and works like youtube shortcuts)
  - `S-j`/S-l`: slow-down/speed-up autoplaying navigator

### PR DESCRIPTION
**Pull request by Harjot1Singh**
Closes #103.

### CODE REVIEW

**Comment by bhajneet** [comment]
Autoselect issue explained via video over slack. Basically if you go to the rahao line from a pauri and activate the second rahao line, then the main rahao line, then autoselect, it will go to the line after secondary rahao line instead of the correct pauri. I suspect that the "jump from"-secondary line is not being stored correctly or it is being updated on up and down arrow keys.

We implemented something for up and down arrow keys where if you hit it too many times it "debounces" (?) and doesn't activate on the screen until the user stops scrolling. This is great for up and down keys. When it comes to combos with up and down arrow + spacebar for autoselect, please do not include this debounce strategy. I don't want any delay. A couple use cases: From secondary rahao line, hit up for main line, hit spacebar for autoselect to go directly from second rahao line to the correct next pauri line. Second example: To go to the second rahao line from the pauri lines, hit the space bar and then the down key quickly. On screen/livestream it looks seamless. The way it is currently working is correct. Don't implement debounce for spacebar.

Up and Down arrow keys are wrapping shabad. Hitting down on last line is going to the first line of the same shabad. It should either not do anything or go to the first line of the next shabad.

**Comment by bhajneet** [comment]
Another issue, the autoselect history is not persisting. If you jump around on one shabad, open a different shabad, then return to the first shabad via history/search it will not remember what pauri/line it needs to jump to from the main line.

**Comment by Harjot1Singh** [comment]
> We implemented something for up and down arrow keys where if you hit it too many times it "debounces" (?) and doesn't activate on the screen until the user stops scrolling. This is great for up and down keys. When it comes to combos with up and down arrow + spacebar for autoselect, please do not include this debounce strategy. I don't want any delay. A couple use cases: From secondary rahao line, hit up for main line, hit spacebar for autoselect to go directly from second rahao line to the correct next pauri line. Second example: To go to the second rahao line from the pauri lines, hit the space bar and then the down key quickly. On screen/livestream it looks seamless. The way it is currently working is correct. Don't implement debounce for spacebar.

Are you saying the way it's currently working in the Navigator is OK?

**Comment by Harjot1Singh** [comment]
> Autoselect issue explained via video over slack. Basically if you go to the rahao line from a pauri and activate the second rahao line, then the main rahao line, then autoselect, it will go to the line after secondary rahao line instead of the correct pauri. I suspect that the "jump from"-secondary line is not being stored correctly or it is being updated on up and down arrow keys.

Hmmm. I can't find the video describing the issue/need more clarity on this. The v1 Shabad OS autoselect behaves the same as what we have right now, as far as I can tell 🤔

**Pull request merged**
