### PR TITLE
Release 2.7.0

### PR DESCRIPTION
**Pull request by Harjot1Singh**

### CODE REVIEW

**Comment by bhajneet** [comment]
Getting this error in browser: 
image

**Comment by saihaj** [comment]
I would suggest clearing out local storage and then run it. If it crashes then we should investigate further. Reason with dev is that localhost is the domain that is used and localstorage has so many things in it as theme-tool also uses it and never gets flushed out properly

**Comment by bhajneet** [comment]
Fix the linting and release is good to go.

Need to resolve punjabi fonts and incorrect citation formatting for next release.

Our list of fixes keeps growing with every new feature implementation. So our next release will strongly focus on severely cutting down our existing fix list before tackling any new features. This is imperative. Discussion and development of new features are to be ceased until Q is empty of bug fixes.

**Comment by saihaj** [comment]
#527 should fix lining errors

**Pull request merged**
