### PR TITLE
Additional overlay themes + settings

### PR DESCRIPTION
**Pull request by Harjot1Singh**
- [x] Overlay themes
- [x] Dropdown of overlay themes
- [x] Display Overlay URL
- [x] New languages

@bhajneet currently the new fields are shown, should they be hidden? Should all themes hide all fields by default, if we're going to have themes?

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
Overlay themes :)

acb59bd4-b45a-4e8e-9813-a981bf15fdcb

**Comment by bhajneet** [comment]
I think there should be an "Example" css file in user directory if possible with all the comments provided in new theme files

**Comment by Harjot1Singh** [comment]
> I think there should be an "Example" css file in user directory if possible with all the comments provided in new theme files

`example.css.template`?

**Comment by Harjot1Singh** [comment]
> Done
> 
> Is there a better way to get settings for both from the same place or to keep these in sync? I don't like the idea of keeping parts of two files identical manually

Neither do I. I left a note in there to make sure that the two are in-sync, but one option is to move that file into the frontend folder and then import those default settings for the backend there (because the frontend can't use anything from outside of it)

**Pull request merged**
