### PR TITLE
Improve touch friendliness on mobile

### PR DESCRIPTION
**Pull request by bhajneet**

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
Autoselect jump to and from is missing I think since you’ve hidden the meta

**Comment by bhajneet** [comment]
Autoselect not missing (simply not shown on bookmarks). Here is an example of a shabad opened from search: 
image

**Comment by bhajneet** [comment]
Autoselect not missing (simply not shown on bookmarks). Here is an example of a shabad opened from search: 
Screenshot_20191202-121023

**Comment by bhajneet** [comment]
> 
> 
> I’d refactor breakpoint values as CSS variables (they’re either in App.css or consts.css)
> 
> Additionally, please ensure rules always have a newline after them

Done

**Comment by Harjot1Singh** [comment]
The meta jump icon is definitely not there on mobile. I reckon you should just keep the hotkey numbers, because they're good mental references anyway (if you're scrolling for e.g. the 4th pauri in anand sahib, that is easier to do)

**Pull request merged**
