### PR TITLE
more info in search results

### LINKED ISSUE #225: show more info on each search result
if we are to include translation/transliteration searches in the future, it would be nice to expose these on the results so they can be highlighted properly.

in the case of transliteration it would be best to highlight both the gurmukhi as well as the translit line.

proposed:

* RAAG AUTHOR SOURCE PAGE:LINE
* MATCH RESULT (depending on search type):
  * GURMUKHI 
  * GURMUKHI + ENGLISH TRANSLATION
  * GURMUKHI + ENGLISH TRANSLIT

### PR DESCRIPTION
**Pull request by saihaj**
* [X] Data from backend 
* [X] Render meta data and translit/ translation in search results 
* [X] Style the results similar to mobile mockup 
* [x] Setting to choose different translation (dropdown)
* [x] Setting to choose different translits (dropdown)
* [x] Add option to hide meta data
~~Tutorial button~~

Let me know if we should allow user to choose metadata and rearrange it to their liking (part of this PR or a new feat)?

Closes #225

### CODE REVIEW

**Comment by saihaj** [comment]
@Harjot1Singh need to fix server settings. Not working because of  f0e060a.
@bhajneet take a look at icons and let me know if we need to change them. 
I need to integrate the settings with the menu options once I figure out how translation will work because of different sources we have. 
Also waiting on how to display source names [View in Slack](https://shabados.slack.com/archives/CD9QC0XKR/p1589312912161800)

**Comment by saihaj** [comment]
https://github.com/ShabadOS/database/issues/1767 will take care of short source names. But will depend on release. So for time being need to make a function that will take care of that. Will need to update once latest version of DB has that feature.

**Comment by saihaj** [comment]
Need to fix full-word search d2739016a1ab989f4ea048c0b61cb5c1af0fb6d2

**Comment by bhajneet** [comment]
image

**Comment by bhajneet** [comment]
Off in dropdown should be "None". Though I still prefer radio buttons for user customizability in case they want to see english and punjabi translation at the same time for instance.

The other option is to add "checkmarks" to dropdown so you select multiple options in each dropdown. This would cut down on space used but still allow the same functionalilty. I don't necessarily think we have the hours to spend on such implementations, so highly recommend the simple radio buttons if possible.

**Comment by bhajneet** [comment]
image

Font weights:
* Punjabi too heavy
* Translit not making matching heavier than non-matching as gurmukhi does

---

image

Line heights:
* Urdu not tall enough

**Comment by bhajneet** [comment]
Fix short titles to use two words for Bhai Nand Laal compositions as per source:

image

**Comment by saihaj** [comment]
My only concern is that it will be messy. Purpose of this is to help Search in some way. If we add an option to choose multiple then we are basically making a Presenter window (that is too long to scroll down). If they want read them they are only click away from that anyway. #419 will also help because we will add all those features into it. 

> english and punjabi translation at the same time for instance

**Comment by Harjot1Singh** [comment]
The search component needs some serious refactoring lol

**Comment by saihaj** [comment]
Probably make search results as a component in future if we do something with #521

**Pull request merged**
