### PR TITLE
Settings Redesign

### LINKED ISSUE #77: Redesigned settings
Quick settings in controller, big settings, new window?

### PR DESCRIPTION
**Pull request by Harjot1Singh**
Adds settings options to configurator, as part of #77.

- [x] Configure different devices
- [x] Change options
- [x] Remove backwards and forwards icons on controller for settings cog

Closes #77

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
Having an issue with HOCs and component composition - MUI animations do not complete because the components are re-rendered, presumably due to the HOC also re-rendering?

**Comment by Harjot1Singh** [comment]
@inderpreet99 @sbaljeet13

**Comment by sbaljeet13** [comment]
- Animation for which component are you referring to? 
- What is expected behavior?

**Comment by Harjot1Singh** [comment]
- The components declared inside `SettingComponent.js`
- The animations should complete, so the toggles, for example, should slide, instead of just re-rendering into the correct state

**Comment by Harjot1Singh** [comment]
@sbaljeet13

**Comment by Harjot1Singh** [comment]
Issues sorted. ESLint needs to be satisfied, then ready to merge

**Pull request merged**
